<a href="https://colab.research.google.com/github/sohyeon1202/ai_python/blob/main/240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#문제2_공백 없이 주어지는 숫자들의 합
num = input()
nums = list(num)
aa = map(int, nums)
print(sum(aa))

In [ ]:
#문제3_리스트 확장자가 png jpg인 파일명만 출력하는 파이썬 코드
n = int(input())
a = [input() for _ in range(n)]
b = [i for i in a if i.split('.')[-1]=='jpg' or i.split('.')[-1]=='png']

패키지는 모듈을 포함함
모듈 = 파이썬 코드를 담고 있는 파이썬 파일.


In [ ]:
pip install pandas

벡터 = 스칼라의 집합
행렬 = 벡터의 집합

함수 : 함수 단독으로 사용
메소드 : 객체명.메소드
객체 속성은 괄호가 안 붙음
넘파이 클래스 기본 속성 잘 알아두깅~!!!(자료 확인에 유용하게 활용)





In [2]:
#1. 1부터 10까지(미포함)의 2걸음 크기의 정수값 배열을 생성해보자.
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#2. 모양이 (3, 4)인 모든 값이 1인 배열을 생성해보자.
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#3. 0과 1사이를 10등분하고자 할 때 등분값 배열을 생성해보자
a = np.linspace(0,1,10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [19]:
a = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])
print('shape : ',a.shape)
print(a[3,3])

print(a[0:2,0:2])
print(a[-2:, -2:])


print(a[0:2, :])
print(a[:, -2:])



shape :  (5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [35]:
a = np.arange(1,37)
b = a.reshape(-1,4,3)
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
